version: '3.9'

volumes:
  amqp:
  postgres:
  redis:

networks:
  default:

services:
  modmail:
    build: ./
    restart: always
    depends_on:
      - postgres
      - rabbitmq
      - redis
      - twilight-dispatch

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - 5432:5432
    env_file:
      - db.env

  rabbitmq:
    image: rabbitmq:management-alpine
    restart: unless-stopped
    volumes:
      - amqp:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - rabbitmq.env

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis:/data
    ports:
      - 6379:6379

  twilight-dispatch:
    image: chamburr/twilight-dispatch:latest
    restart: unless-stopped
    depends_on:
      - amqp
      - redis
    env_file:
      - twilight-dispatch.env
