version: '3.9'

volumes:
  rabbitmq:
  postgres:
  redis:

networks:
  default:

services:
  modmail:
    build: ./
    restart: always
    depends_on:
      - postgres
      - rabbitmq
      - redis
      - twilight-dispatch

  postgres:
    image: postgres:alpine
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - db.env

  rabbitmq:
    image: rabbitmq:management-alpine
    restart: always
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - rabbitmq.env

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis:/data
    ports:
      - 6379:6379

  twilight-dispatch:
    image: chamburr/twilight-dispatch:latest
    restart: always
    depends_on:
      - rabbitmq
      - redis
    env_file:
      - twilight-dispatch.env
