version: '3.9'

volumes:
  amqp:  
  postgres:
  redis:

networks:
  default:

services:
  app:
    build: ./
    command: sh -c 'scripts/wait.sh amqp:5672 -- python3 -u launcher.py'
    restart: unless-stopped
    depends_on:
      - amqp
      - postgres
      - redis
      - twilight-dispatch
  
  amqp:
    image: rabbitmq:management-alpine
    restart: unless-stopped
    volumes:
      - amqp:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    
  postgres:
    image: postgres:alpine 
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - 5432:5432
    env_file:
      - db.env

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis:/data
    ports:
      - 6379:6379

  twilight-dispatch:
    image: chamburr/twilight-dispatch:latest
    restart: unless-stopped
    network_mode: host
    depends_on:
      - amqp
      - redis
    env_file:
      - .env
